BookStore
AhmadiGu/BookStore pull request #3
Opened 2023-01-04 16:41 UTC by AhmadiGu

### Connect redux to react

- add provider
- use hooks useSelector, useDispitch 
-  able to add and remove functionalities

2023-01-04 17:40 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @AhmadiGu, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ All linters passing 
✔️ Correct gitflow
✔️ Professional readme

## Required 
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 17:40 UTC, sja-thedude commented on src/redux/categories/categories.js
> +};
- [ ] As per the requirements, kindly make sure to display "Under Construction" when the Check status button is clicked.

https://user-images.githubusercontent.com/70269507/210616018-e045b40d-a37e-44a3-8b01-c700199f27bd.mov

2023-01-05 09:48 UTC, danmainah approved these changes
Hi @AhmadiGu , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ No linter errors
✔️ Gitflow was correctly used
✔️  Good design

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-05 09:48 UTC, danmainah commented on README.md
> +
- [ ] [optional] It would have been nice if you added a future feature section in your readme file.

2023-05-21 09:13 UTC, merged